/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.pengolahan.data.pada.peternakan.ayam.broiler;

/**
 *
 * @author IQBAL
 */
public class Data_karyawan extends javax.swing.JFrame {

    /**
     * Creates new form Data_karyawan
     */
    public Data_karyawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        karyawan = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        edit = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        idkaryawan1 = new javax.swing.JLabel();
        nama1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        nik1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        tempat1 = new javax.swing.JLabel();
        tanggal1 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jk1 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        agam1 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        pendidikan1 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox8 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        HOME = new javax.swing.JMenu();
        datakaryawan = new javax.swing.JMenu();
        datadistributor = new javax.swing.JMenu();
        dtakndg = new javax.swing.JMenu();
        dtaayam = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        karyawan.setBackground(new java.awt.Color(102, 102, 102));
        karyawan.setForeground(new java.awt.Color(255, 255, 255));
        karyawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        karyawan.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 719, -1, -1));

        edit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-compose-40.png")); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        karyawan.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 538, 40, 40));

        tambah.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-add-new-40.png")); // NOI18N
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        karyawan.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 40, 40));

        simpan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-save-40.png")); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        karyawan.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 40, 40));

        batal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        batal.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-close-window-40.png")); // NOI18N
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        karyawan.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 40, 40));
        karyawan.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 250, -1));

        idkaryawan1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idkaryawan1.setForeground(new java.awt.Color(255, 255, 255));
        idkaryawan1.setText("ID karyawan");
        karyawan.add(idkaryawan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        nama1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nama1.setForeground(new java.awt.Color(255, 255, 255));
        nama1.setText("NAMA");
        karyawan.add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        karyawan.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 250, -1));
        karyawan.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 250, -1));

        nik1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nik1.setForeground(new java.awt.Color(255, 255, 255));
        nik1.setText("NIK");
        karyawan.add(nik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        karyawan.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 250, -1));

        tempat1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tempat1.setForeground(new java.awt.Color(255, 255, 255));
        tempat1.setText("Tempat Lahir");
        karyawan.add(tempat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        tanggal1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tanggal1.setForeground(new java.awt.Color(255, 255, 255));
        tanggal1.setText("Tanggal Lahir");
        karyawan.add(tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        karyawan.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 21));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        karyawan.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jk1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jk1.setForeground(new java.awt.Color(255, 255, 255));
        jk1.setText("Jenis Kelamin");
        karyawan.add(jk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jRadioButton3.setText("Laki - laki");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        karyawan.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        agam1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        agam1.setForeground(new java.awt.Color(255, 255, 255));
        agam1.setText("Agama");
        karyawan.add(agam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Islam", "Kristen", "Hindu", "Budha", "Sinto", "Konghucu" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        karyawan.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        pendidikan1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pendidikan1.setForeground(new java.awt.Color(255, 255, 255));
        pendidikan1.setText("Pendidikan");
        karyawan.add(pendidikan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "SD/MI", "SMP/MTS", "SMA/SMK/MA", "Diploma 3", "S1" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        karyawan.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA KARYAWAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jRadioButton4.setText("Perempuan");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(90, 90, 90))
        );

        karyawan.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 410, 360));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PENEMPATAN KANDANG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID kandang");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jabatan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "1", "2" }));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Masuk");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Statu Kerja");

        jCheckBox1.setText("Aktif");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));
        jSpinner1.setToolTipText("");
        jSpinner1.setName("Tanggal"); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jCheckBox2.setText("Non-Aktif");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(85, 85, 85)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(63, 63, 63)
                        .addComponent(jCheckBox1)
                        .addGap(33, 33, 33)
                        .addComponent(jCheckBox2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        karyawan.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 400, 210));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\4 SEMESTER\\PBO\\gambar ayam pbo\\Cara-Merawat-DOC-Ayam-2.jpg")); // NOI18N
        karyawan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 1080, 880));

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        HOME.setText("Home");
        HOME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HOME.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                HOMEMenuSelected(evt);
            }
        });
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });
        jMenuBar1.add(HOME);

        datakaryawan.setText("Data Karyawan");
        datakaryawan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datakaryawan.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                datakaryawanMenuSelected(evt);
            }
        });
        datakaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datakaryawanMouseClicked(evt);
            }
        });
        datakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakaryawanActionPerformed(evt);
            }
        });
        jMenuBar1.add(datakaryawan);

        datadistributor.setText("Data Distributor");
        datadistributor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datadistributor.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                datadistributorMenuSelected(evt);
            }
        });
        datadistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datadistributorActionPerformed(evt);
            }
        });
        jMenuBar1.add(datadistributor);

        dtakndg.setText("Data Kandang");
        dtakndg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtakndg.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtakndgMenuSelected(evt);
            }
        });
        dtakndg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtakndgActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtakndg);

        dtaayam.setText("Kebutuhan Ayam");
        dtaayam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtaayam.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtaayamMenuSelected(evt);
            }
        });
        dtaayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtaayamActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtaayam);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datakaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datakaryawanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_datakaryawanMouseClicked

    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
        // TODO add your handling code here:
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HOMEActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here
        pkaryawan as = new pkaryawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editActionPerformed

    private void datakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakaryawanActionPerformed
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datakaryawanActionPerformed

    private void datadistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datadistributorActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datadistributorActionPerformed

    private void dtakndgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtakndgActionPerformed
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakndgActionPerformed

    private void dtaayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtaayamActionPerformed
        // TODO add your handling code here:
        kebutuhanayam as = new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtaayamActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tambahActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void HOMEMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_HOMEMenuSelected
        // TODO add your handling code here:
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HOMEMenuSelected

    private void datakaryawanMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_datakaryawanMenuSelected
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datakaryawanMenuSelected

    private void datadistributorMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_datadistributorMenuSelected
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datadistributorMenuSelected

    private void dtakndgMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtakndgMenuSelected
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakndgMenuSelected

    private void dtaayamMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtaayamMenuSelected
        // TODO add your handling code here:
        kebutuhanayam as = new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtaayamMenuSelected

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu HOME;
    private javax.swing.JLabel agam1;
    private javax.swing.JButton batal;
    private javax.swing.JMenu datadistributor;
    private javax.swing.JMenu datakaryawan;
    private javax.swing.JMenu dtaayam;
    private javax.swing.JMenu dtakndg;
    private javax.swing.JButton edit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel idkaryawan1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel jk1;
    private javax.swing.JPanel karyawan;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nik1;
    private javax.swing.JLabel pendidikan1;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel tanggal1;
    private javax.swing.JLabel tempat1;
    // End of variables declaration//GEN-END:variables
}
