/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.pengolahan.data.pada.peternakan.ayam.broiler;

/**
 *
 * 
 */
public class Data_distributor extends javax.swing.JFrame {

    /**
     * Creates new form Data_distributor
     */
    public Data_distributor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        dtakarya = new javax.swing.JMenu();
        dtadistri = new javax.swing.JMenu();
        dtaknda = new javax.swing.JMenu();
        dtaayam = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(822, 600));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Distributor");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 150, 130, 19);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA DISTRIBUTOR ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 70, 250, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Pengirim");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 210, 140, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Institusi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 180, 100, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Kiriman");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 250, 140, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga/Ekor");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 280, 110, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 320, 100, 19);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah  Tanggungan (Rp)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 360, 180, 19);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(360, 150, 183, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(360, 180, 183, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(360, 210, 183, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(360, 240, 183, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(360, 280, 183, 20);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(360, 320, 39, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(400, 320, 77, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(490, 320, 55, 20);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(360, 360, 183, 20);

        edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-compose-40.png")); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(190, 440, 40, 40);

        tambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-add-new-40.png")); // NOI18N
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(340, 440, 40, 40);

        simpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-save-40.png")); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(480, 440, 40, 40);

        batal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batal.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-close-window-40.png")); // NOI18N
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal);
        batal.setBounds(600, 440, 40, 40);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 120, 530, 290);

        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\4 SEMESTER\\PBO\\gambar ayam pbo\\DOC-Ayam-Kampung-Jakarta.jpg")); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 750, 620);

        home.setText("Home");
        home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        home.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                homeMenuSelected(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenuBar1.add(home);

        dtakarya.setText("Data Karyawan");
        dtakarya.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtakarya.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtakaryaMenuSelected(evt);
            }
        });
        dtakarya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtakaryaActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtakarya);

        dtadistri.setText("Data Distributor");
        dtadistri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtadistri.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtadistriMenuSelected(evt);
            }
        });
        dtadistri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtadistriActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtadistri);

        dtaknda.setText("Data Kandang");
        dtaknda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtaknda.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtakndaMenuSelected(evt);
            }
        });
        dtaknda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtakndaActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtaknda);

        dtaayam.setText("Kebutuhan Ayam");
        dtaayam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtaayam.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtaayamMenuSelected(evt);
            }
        });
        dtaayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtaayamActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtaayam);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void dtakaryaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtakaryaActionPerformed
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakaryaActionPerformed

    private void dtadistriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtadistriActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtadistriActionPerformed

    private void dtakndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtakndaActionPerformed
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakndaActionPerformed

    private void dtaayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtaayamActionPerformed
        // TODO add your handling code here:
        kebutuhanayam as = new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtaayamActionPerformed

    private void homeMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_homeMenuSelected
        // TODO add your handling code here:
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMenuSelected

    private void dtakaryaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtakaryaMenuSelected
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakaryaMenuSelected

    private void dtadistriMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtadistriMenuSelected
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtadistriMenuSelected

    private void dtakndaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtakndaMenuSelected
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakndaMenuSelected

    private void dtaayamMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtaayamMenuSelected
        // TODO add your handling code here:
        kebutuhanayam as = new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtaayamMenuSelected

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        pdistributor as = new pdistributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tambahActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_distributor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JMenu dtaayam;
    private javax.swing.JMenu dtadistri;
    private javax.swing.JMenu dtakarya;
    private javax.swing.JMenu dtaknda;
    private javax.swing.JButton edit;
    private javax.swing.JMenu home;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
