/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.pengolahan.data.pada.peternakan.ayam.broiler;

/**
 *
 * @author IQBAL
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dtkaryawan = new javax.swing.JButton();
        dtkandang = new javax.swing.JButton();
        dtdistributor = new javax.swing.JButton();
        kebutuhanayam = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        icnkar = new javax.swing.JLabel();
        icndistri = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        dtakarya = new javax.swing.JMenu();
        dtadistri = new javax.swing.JMenu();
        dtakandg = new javax.swing.JMenu();
        dtayam = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        dtkaryawan.setBackground(new java.awt.Color(255, 255, 255));
        dtkaryawan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dtkaryawan.setText("DATA KARAYAWAN");
        dtkaryawan.setAutoscrolls(true);
        dtkaryawan.setBorder(null);
        dtkaryawan.setBorderPainted(false);
        dtkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtkaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(dtkaryawan);
        dtkaryawan.setBounds(110, 120, 141, 50);

        dtkandang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dtkandang.setText("DATA KANDANG");
        dtkandang.setAutoscrolls(true);
        dtkandang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        dtkandang.setBorderPainted(false);
        dtkandang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtkandangActionPerformed(evt);
            }
        });
        jPanel1.add(dtkandang);
        dtkandang.setBounds(620, 130, 169, 50);

        dtdistributor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dtdistributor.setText("DATA DISTRIBUTOR");
        dtdistributor.setAutoscrolls(true);
        dtdistributor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        dtdistributor.setBorderPainted(false);
        dtdistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtdistributorActionPerformed(evt);
            }
        });
        jPanel1.add(dtdistributor);
        dtdistributor.setBounds(106, 294, 141, 50);

        kebutuhanayam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        kebutuhanayam.setText("KEBUTUHAN AYAM");
        kebutuhanayam.setAutoscrolls(true);
        kebutuhanayam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        kebutuhanayam.setBorderPainted(false);
        kebutuhanayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebutuhanayamActionPerformed(evt);
            }
        });
        jPanel1.add(kebutuhanayam);
        kebutuhanayam.setBounds(620, 290, 169, 50);

        edit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-compose-40.png")); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(170, 440, 40, 40);

        tambah.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-save-40.png")); // NOI18N
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(470, 440, 40, 40);

        simpan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-add-new-40.png")); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(320, 440, 40, 40);

        batal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        batal.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-close-window-40.png")); // NOI18N
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal);
        batal.setBounds(633, 443, 40, 40);
        jPanel1.add(icnkar);
        icnkar.setBounds(88, 80, 0, 0);
        jPanel1.add(icndistri);
        icndistri.setBounds(88, 344, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-identification-documents-80 (1).png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 110, 80, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-track-order-80.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 260, 80, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-farm-house-80.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 110, 80, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\icons8-chicken-foster-80.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(540, 270, 80, 70);

        bg.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\4 SEMESTER\\PBO\\ayam broiler\\chickdrinking_forweb.jpg")); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-130, 0, 970, 660);

        home.setText("Home");
        home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        home.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                homeMenuSelected(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenuBar1.add(home);

        dtakarya.setText("Data Karyawan");
        dtakarya.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtakarya.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtakaryaMenuSelected(evt);
            }
        });
        dtakarya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtakaryaActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtakarya);

        dtadistri.setText("Data Distributor");
        dtadistri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtadistri.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtadistriMenuSelected(evt);
            }
        });
        dtadistri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtadistriActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtadistri);

        dtakandg.setText("Data kandang");
        dtakandg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtakandg.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtakandgMenuSelected(evt);
            }
        });
        dtakandg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtakandgActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtakandg);

        dtayam.setText("Kebutuhan Ayam");
        dtayam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtayam.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtayamMenuSelected(evt);
            }
        });
        dtayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtayamActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtayam);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void dtkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtkaryawanActionPerformed
        Data_karyawan as =  new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtkaryawanActionPerformed

    private void dtkandangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtkandangActionPerformed
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtkandangActionPerformed

    private void dtdistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtdistributorActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtdistributorActionPerformed

    private void kebutuhanayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebutuhanayamActionPerformed
        // TODO add your handling code here:
        kebutuhanayam as =  new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kebutuhanayamActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
         Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_simpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
         Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void dtakaryaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtakaryaActionPerformed
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakaryaActionPerformed

    private void dtadistriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtadistriActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtadistriActionPerformed

    private void dtakandgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtakandgActionPerformed
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakandgActionPerformed

    private void dtayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtayamActionPerformed
        // TODO add your handling code here:
        kebutuhanayam as = new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtayamActionPerformed

    private void homeMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_homeMenuSelected
        // TODO add your handling code here:
        Home as =  new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMenuSelected

    private void dtakaryaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtakaryaMenuSelected
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakaryaMenuSelected

    private void dtadistriMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtadistriMenuSelected
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtadistriMenuSelected

    private void dtakandgMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtakandgMenuSelected
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakandgMenuSelected

    private void dtayamMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtayamMenuSelected
        // TODO add your handling code here:
        kebutuhanayam as = new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtayamMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JLabel bg;
    private javax.swing.JMenu dtadistri;
    private javax.swing.JMenu dtakandg;
    private javax.swing.JMenu dtakarya;
    private javax.swing.JMenu dtayam;
    private javax.swing.JButton dtdistributor;
    private javax.swing.JButton dtkandang;
    private javax.swing.JButton dtkaryawan;
    private javax.swing.JButton edit;
    private javax.swing.JMenu home;
    private javax.swing.JLabel icndistri;
    private javax.swing.JLabel icnkar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kebutuhanayam;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
