/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.pengolahan.data.pada.peternakan.ayam.broiler;

/**
 *
 * @author Cindy
 */
public class kebutuhanayam extends javax.swing.JFrame {

    /**
     * Creates new form kebutuhanayam
     */
    public kebutuhanayam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        edit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        dtakaryawan = new javax.swing.JMenu();
        dtadistribusi = new javax.swing.JMenu();
        dtakandang = new javax.swing.JMenu();
        dtayam = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(882, 600));
        jPanel1.setLayout(null);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+3));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Pakan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 110, 80, 17);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pakan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 140, 100, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Supplier");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 70, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 200, 60, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Berat Kemasan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 230, 106, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 270, 50, 19);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Umur Pemberian");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 360, 116, 19);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bentuk");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 310, 70, 19);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 110, 190, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(180, 140, 190, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(180, 170, 190, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(180, 200, 157, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(180, 230, 157, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "STARTER", "GROWER", "FINISHER" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(180, 270, 100, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(180, 360, 157, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "CRUMBLE", "CONCENTRAT", "PELLET" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(180, 310, 100, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Rp");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 200, 15, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kg");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 230, 14, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hari");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(350, 360, 23, 14);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID Pakan");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(480, 140, 80, 19);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID Jadwal");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(480, 100, 90, 19);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Jam Makan");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(480, 170, 90, 19);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jumlah Pembelian");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(480, 210, 127, 19);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tanggal");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(480, 250, 55, 19);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA PAKAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 60, 410, 360);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(670, 250, 60, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(740, 250, 60, 20);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(630, 250, 39, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(620, 100, 186, 20);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(620, 140, 180, 20);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(620, 170, 134, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("WIB");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(760, 170, 40, 20);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(620, 210, 184, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Kg");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(740, 140, 14, 14);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA PEMBERIAN PAKAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(450, 60, 410, 250);

        edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\4 SEMESTER\\PBO\\gambar ayam pbo\\edit.PNG")); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(230, 480, 40, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\4 SEMESTER\\PBO\\gambar ayam pbo\\tambah.PNG")); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(368, 482, 40, 40);

        simpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\4 SEMESTER\\PBO\\gambar ayam pbo\\simpan.PNG")); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(523, 482, 40, 40);

        batal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batal.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\4 SEMESTER\\PBO\\gambar ayam pbo\\batal.PNG")); // NOI18N
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal);
        batal.setBounds(673, 482, 40, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\4 SEMESTER\\PBO\\gambar ayam pbo\\Cara-Merawat-DOC-Ayam-2.jpg")); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(0, -60, 920, 730);

        home.setText("Home");
        home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        home.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                homeMenuSelected(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenuBar1.add(home);

        dtakaryawan.setText("Data Karyawan");
        dtakaryawan.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtakaryawanMenuSelected(evt);
            }
        });
        dtakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtakaryawanActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtakaryawan);

        dtadistribusi.setText("Data Distribusi");
        dtadistribusi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtadistribusi.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtadistribusiMenuSelected(evt);
            }
        });
        dtadistribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtadistribusiActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtadistribusi);

        dtakandang.setText("Data Kandang");
        dtakandang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtakandang.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtakandangMenuSelected(evt);
            }
        });
        dtakandang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtakandangActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtakandang);

        dtayam.setText("Kebutuhan Ayam");
        dtayam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dtayam.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                dtayamMenuSelected(evt);
            }
        });
        dtayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtayamActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtayam);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Home as = new Home ();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void dtakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtakaryawanActionPerformed
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakaryawanActionPerformed

    private void dtadistribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtadistribusiActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtadistribusiActionPerformed

    private void dtakandangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtakandangActionPerformed
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakandangActionPerformed

    private void dtayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtayamActionPerformed
        // TODO add your handling code here:
        kebutuhanayam as = new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtayamActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        pkebutuhan as = new pkebutuhan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_simpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        Data_distributor as = new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void homeMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_homeMenuSelected
        // TODO add your handling code here:
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMenuSelected

    private void dtakaryawanMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtakaryawanMenuSelected
        // TODO add your handling code here:
        Data_karyawan as = new Data_karyawan();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakaryawanMenuSelected

    private void dtadistribusiMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtadistribusiMenuSelected
        // TODO add your handling code here:
        Data_distributor as =  new Data_distributor();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtadistribusiMenuSelected

    private void dtakandangMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtakandangMenuSelected
        // TODO add your handling code here:
        Kandang as = new Kandang();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtakandangMenuSelected

    private void dtayamMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_dtayamMenuSelected
        // TODO add your handling code here:
        kebutuhanayam as = new kebutuhanayam();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dtayamMenuSelected

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kebutuhanayam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kebutuhanayam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kebutuhanayam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kebutuhanayam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kebutuhanayam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JMenu dtadistribusi;
    private javax.swing.JMenu dtakandang;
    private javax.swing.JMenu dtakaryawan;
    private javax.swing.JMenu dtayam;
    private javax.swing.JButton edit;
    private javax.swing.JMenu home;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
